---
- hosts: typo3
  tasks:
  - name: ensure user exists
    hsuser.js: name="{{pac}}-{{user}}" password="{{password}}" exists="true"
  - name: setup domain
    hsdomain.js: name="{{domain}}" owner="{{pac}}-{{user}}" exists="true"
  - name: ensure database exists
    hsdatabase.js: name="{{pac}}_{{user}}" password="{{password}}" instance="mysql" exists="true"
  - name: download newest typo3 6.2 release
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: wget get.typo3.org/6.2 -O typo3_src.tgz chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: make typo3_src directoryl
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: mkdir typo3_src chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: extract tarball
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: tar -xvzf typo3_src.tgz -C typo3_src/ --strip-components=1 chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: remove .tgz file
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: rm -f typo3_src.tgz chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: remove www directory
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: rm -rf www chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: rename typo3_src directory to www
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: mv typo3_src www chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: create FIRST_INSTALL file
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: touch FIRST_INSTALL chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs/www"
